to be squashed

diff --git a/.github/workflows/automatic-update.yml b/.github/workflows/automatic-update.yml
--- a/.github/workflows/automatic-update.yml
+++ b/.github/workflows/automatic-update.yml
@@ -49,8 +49,11 @@ jobs:
             ANSIBLE_CORE_VERSION=$(curl -sSf "https://pypi.org/pypi/ansible-core/json" | jq -r '.info.version')
           fi
 
+          # Each deps file created with a version of ansible-build-data has an ansible-core version
+          ## Versions are tracked as alpha, beta, etc and written in the deps filename.
+          ## Get the mos recent deps file using the selected ansible-core version.
           DEPS_FILE=$( find ./ -type f -name ansible-\*\.deps \
-            -exec grep -E -l '^_ansible_core_version: '"${ANSIBLE_CORE_VERSION}"'$' {} \; \
+            -exec grep -E -l "^_ansible_core_version: ${ANSIBLE_CORE_VERSION}\$" {} \; \
           	| while read -r line; do
               ver=$(echo "$line" | sed -n 's/.*ansible-\([0-9.]\+[a-z0-9]*\)\.deps/\1/p')
               tver=$(echo "$ver" \
@@ -58,8 +61,9 @@ jobs:
                   | sed 's/b\([0-9][0-9]*\)/~beta\1/g'  \
                   | sed 's/rc\([0-9][0-9]*\)/~rc\1/g')
               echo "$tver $line"
-          done  | sort -V | sed 's/^[^ ]* //' | tail -n 1)
+          done | sort -V | sed 's/^[^ ]* //' | tail -n 1)
 
+          ## Get the version using from the file name
           ANSIBLE_COMMUNITY_VERSION=$(echo "${DEPS_FILE}" | sed -n 's/.*ansible-\([0-9.]\+[a-z0-9]*\)\.deps/\1/p')
 
           echo "ANSIBLE_CORE_VERSION=$ANSIBLE_CORE_VERSION" >> "$GITHUB_ENV"
@@ -118,13 +122,15 @@ jobs:
           IMAGE_NAME: ${{ github.repository_owner }}/${{ inputs.ee-name }}
         run: |
           sudo apt install podman --yes
+          set -x
           EE_VERSION="$( \
             podman search --format '{{.Tag}}' \
               --list-tags ghcr.io/${IMAGE_NAME} | \
-            grep -- '${ANSIBLE_CORE_VERSION}-' | \
-            awk -F'-' '{ if (NF > 1 && $2 ~ /^[0-9]+$/) { print $2 + 1; found=1 } } END { if (!found) print 1 }'
+            grep -- "${ANSIBLE_CORE_VERSION}-" | \
+            awk -F'-' '{ if (NF > 1 && $2 ~ /^[0-9]+$/) { print $2 + 1; found=1 } } END { if (!found) print 1 }' \
+            || true \
           )"
-          echo "EE_VERSION=${EE_VERSION}"
+
           echo "EE_VERSION=${EE_VERSION}" >> "$GITHUB_ENV"
 
           echo "ANSIBLE_BRANCH_NAME=ansible-core-${ANSIBLE_CORE_VERSION}-${EE_VERSION}_${ANSIBLE_COMMUNITY_VERSION}" >> "$GITHUB_ENV"
@@ -166,7 +172,7 @@ jobs:
             git commit -m "${CI_COMMIT_MESSAGE}"
             git branch
             git push origin -f "${ANSIBLE_BRANCH_NAME}"
-            echo "✅ Changes committed and pushed to branch ${ANSIBLE_BRANCH_NAME}" | tee -a "$GITHUB_STEP_SUMMARY"
+            echo "ℹ️ Changes committed and pushed to branch ${ANSIBLE_BRANCH_NAME}" | tee -a "$GITHUB_STEP_SUMMARY"
             echo "changes=true" >> "$GITHUB_OUTPUT"
           fi
         shell: bash
@@ -198,7 +204,8 @@ jobs:
             2>&1) || PR_CREATED=$?
 
           if [ -z "${PR_URL}" ] || [ "${PR_CREATED}" -ne 0 ]; then
-            echo "⚠️ PR creation failed or PR already exists for branch ${ANSIBLE_BRANCH_NAME}" | tee -a "$GITHUB_STEP_SUMMARY"
+            echo "Branch ${ANSIBLE_BRANCH_NAME} already exists and was updated" | tee -a "$GITHUB_STEP_SUMMARY"
+            echo "⚠️ PR creation failed or PR already exists for the branch" | tee -a "$GITHUB_STEP_SUMMARY"
           else
             echo "✅ PR created: ${PR_URL}" | tee -a "$GITHUB_STEP_SUMMARY"
           fi
